### ISSUE TITLE
https://en.vertilux.com/dealers.html With errors

### ISSUE THREAD

**Issue by albenizpalma** [vertilux/vertilux-homepage#1]
https://en.vertilux.com/dealers.html 

They need to do changes 
the Authorized Dealers Box is not working correctly and displaying an error message.
This bellow is a comment generated by Craig: 

_" we suggest we take a proactive approach and remove the current list of fabricators while replacing it with a blank information form that customers can fill out with their Name, Phone Number, Email Address, and Product Interested in. This form would automatically be sent to our info@vertilux.com](mailto:info@vertilux.com) email address, providing us with a better understanding of the customer's needs and allowing us to forward their contact information to an appropriate fabricator in their area. "

**Comment by lepepe** [comment]
@albenizpalma @mirkopiccone closing this issue.


![Image](https://github.com/vertilux/vertilux-homepage/assets/12739553/d8b9ea01-1035-4b37-8466-b8a262000f07)

**Comment by lepepe** [comment]
@albenizpalma  Listo! Form updated and tested processing emails including new inputs:

![Image](https://github.com/vertilux/vertilux-homepage/assets/12739553/55c01897-11e6-4eca-aa50-74dbef65c6c0)
