### ISSUE TITLE
New Landing Page Vertilux Contact form

### ISSUE THREAD

**Issue by albenizpalma** [vertilux/vertilux-homepage#2]

**Comment by albenizpalma** [comment]
https://en.vertilux.com/contact.html basado en esta forma, crear una nueva no asociada, con los mismos campos dirigidos a info@vertilux.com pero el footer y el header solo deben de tener un link a la pagina de Vertilux. 

Eliminar todos los números de telefonos y las filiales.  la unica forma de contacto tiene que ser la forma.

Campo a a agregar. influencercode. 

podría ser algo como:

https://en.vertilux.com/influencer.html

**Comment by lepepe** [comment]
@albenizpalma La nueva pagina de contacto ya fue creada con el mismo URL: https://en.vertilux.com/influencer.html; envie un email de prueba y debe estar funcionando correctamente.


![Image](https://github.com/vertilux/vertilux-homepage/assets/12739553/eac3b2e2-466e-4758-bd75-e9c7765322ae)

CC: @mirkopiccone
